# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Codes/Vivado/2016/cpu/cpu.srcs/sources_1/ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Codes/Vivado/2016/cpu/cpu.srcs/sources_1/ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Codes/Vivado/2016/cpu/cpu.srcs/sources_1/ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Codes/Vivado/2016/cpu/cpu.srcs/sources_1/ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
